= Red Hat Advanced Cluster Management 2.13 Demonstration Script
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:source-highlighter: rouge
:imagesdir: ./images

_Updated: June, 2025_

[abstract]
The purpose of this document is to provide the user a guided tour of the Red Hat Advanced Cluster Management (RHACM) product. It is intended for internal consumption for the broader RHACM community. At each stage of a live demo, we surface key value propositions and competitive advantages. All of these are persona based so be aware of who you are speaking to. This is a working document that will be amended with each release of the product.

== Introduction

This section covers the initial assessment questions, demo narrative, and buyer personas.

=== Key Customer Assessment Questions

* How many OpenShift clusters do you currently have deployed?
* How are you managing them today? Individually? Centrally?
* Do you have clusters deployed across multiple clouds? (Private + Public)
* Are you using non-OpenShift clusters in your public clouds?
* If you are using a single OpenShift cluster today, are you planning to grow?
* Are you just starting to deploy applications to your OpenShift clusters?
* Do you have any security/governance in place for your clusters and applications?
* Are you using any Kubernetes Management tools today?

=== Demo Narrative

The Narrative is based on who you are speaking to from the customer. Make sure you understand where the customer is on their Kubernetes journey and follow the storyboard.

=== Buyer Personas

[options="header"]
|===
|Persona |Buyer Need(s) |How the Product(s) Fulfills the Need

|IT Ops
|Overall cluster health maintenance and quick root cause analysis
|
* Manage the lifecycle of multiple clusters regardless of where they reside
* Quickly get to the root cause of failed components
* Monitor usage across multiple clouds

|DevOps/SRE
|Ensure application availability and simplified scaling
|
* Get a simplified understanding of my cluster health and the impact it may have on my application availability
* Automate provisioning/ deprovisioning of my clusters
* Automate pushing application updates from dev to prod

|Security Ops
|Ensuring compliance and enforcing security policies across clusters
|
* Ensure all my clusters are compliant with my defined policies
* Set consistent security policies across diverse environments and ensure enforcement
* Get alerted on any configuration drift and remediate it
|===

= Red Hat Advanced Cluster Management 2.13 Demonstration Script
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:source-highlighter: rouge
:imagesdir: ./images

_Updated: June, 2025_

[abstract]
The purpose of this document is to provide the user a guided tour of the Red Hat Advanced Cluster Management (RHACM) product. It is intended for internal consumption for the broader RHACM community. At each stage of a live demo, we surface key value propositions and competitive advantages. All of these are persona based so be aware of who you are speaking to. This is a working document that will be amended with each release of the product.

== Introduction

This section covers the initial assessment questions, demo narrative, and buyer personas.

=== Key Customer Assessment Questions

* How many OpenShift clusters do you currently have deployed?
* How are you managing them today? Individually? Centrally?
* Do you have clusters deployed across multiple clouds? (Private + Public)
* Are you using non-OpenShift clusters in your public clouds?
* If you are using a single OpenShift cluster today, are you planning to grow?
* Are you just starting to deploy applications to your OpenShift clusters?
* Do you have any security/governance in place for your clusters and applications?
* Are you using any Kubernetes Management tools today?

=== Demo Narrative

The Narrative is based on who you are speaking to from the customer. Make sure you understand where the customer is on their Kubernetes journey and follow the storyboard.

=== Buyer Personas

[options="header"]
|===
|Persona |Buyer Need(s) |How the Product(s) Fulfills the Need

|IT Ops
|Overall cluster health maintenance and quick root cause analysis
|
* Manage the lifecycle of multiple clusters regardless of where they reside
* Quickly get to the root cause of failed components
* Monitor usage across multiple clouds

|DevOps/SRE
|Ensure application availability and simplified scaling
|
* Get a simplified understanding of my cluster health and the impact it may have on my application availability
* Automate provisioning/ deprovisioning of my clusters
* Automate pushing application updates from dev to prod

|Security Ops
|Ensuring compliance and enforcing security policies across clusters
|
* Ensure all my clusters are compliant with my defined policies
* Set consistent security policies across diverse environments and ensure enforcement
* Get alerted on any configuration drift and remediate it
|===
